# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kf5-kwallet

# >> macros
# << macros

Summary:    KDE Frameworks 5 Tier 3 solution for password management
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kf5-kwallet.yaml
Source101:  kf5-kwallet-rpmlintrc
Requires:   kf5-filesystem
Requires:   kf5-kwallet-libs%{?_isa} = %{version}-%{release}
Requires:   kf5-kwallet-runtime%{?_isa} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(libgcrypt)
BuildRequires:  pkgconfig(libgpg-error)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kwindowsystem-devel
BuildRequires:  kf5-kcoreaddons-devel
BuildRequires:  kf5-kdbusaddons-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kiconthemes-devel
BuildRequires:  kf5-knotifications-devel
BuildRequires:  kf5-kservice-devel
BuildRequires:  kf5-kwidgetsaddons-devel
BuildRequires:  kf5-kwindowsystem-devel

%description
KDE Frameworks 5 Tier 3 solution for password management


%package libs
Summary:    KWallet framework libraries
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-filesystem
Provides:   kf5-kwallet-api = %{version}-%{release}
Provides:   kf5-kwallet-api%{?_isa} = %{version}-%{release}

%description libs
Provides API to access KWallet data from applications.


%package runtime
Summary:    KWallet runtime deamon
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description runtime
Provides a runtime deamon that stores passwords.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-kwallet-libs%{?_isa} = %{version}-%{release}
Requires:   kf5-kconfig-devel
Requires:   kf5-kwindowsystem-devel
Requires:   kf5-kcoreaddons-devel
Requires:   kf5-kdbusaddons-devel
Requires:   kf5-ki18n-devel
Requires:   kf5-kiconthemes-devel
Requires:   kf5-knotifications-devel
Requires:   kf5-kservice-devel
Requires:   kf5-kwidgetsaddons-devel
Requires:   kf5-kwindowsystem-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
# >> files
# << files

%files libs
%defattr(-,root,root,-)
%{_kf5_libdir}/libKF5Wallet.so.*
%{_kf5_libdir}/libkwalletbackend5.so.*
# >> files libs
# << files libs

%files runtime
%defattr(-,root,root,-)
%{_kf5_datadir}/dbus-1/services/org.kde.kwalletd5.service
%{_kf5_bindir}/kwalletd5
%{_kf5_datadir}/kservices5/kwalletd5.desktop
%{_kf5_datadir}/knotifications5/kwalletd.notifyrc
# >> files runtime
# << files runtime

%files devel
%defattr(-,root,root,-)
%{_kf5_datadir}/dbus-1/interfaces/kf5_org.kde.KWallet.xml
%{_kf5_includedir}/kwallet_version.h
%{_kf5_includedir}/KWallet
%{_kf5_libdir}/cmake/KF5Wallet
%{_kf5_libdir}/libKF5Wallet.so
%{_kf5_libdir}/libkwalletbackend5.so
%{_datadir}/qt5/mkspecs/modules/qt_KWallet.pri
# >> files devel
# << files devel
